---
id: sanmokukai-2016-11-17
base_name: mroonga
tags:
- rabbit
- mroonga
- 3moku
presentation_date: 2016-11-17
version: 2016.11.17.2
licenses:
- CC BY-SA 4.0
slideshare_id: sanmokukai-2016-11-17
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
